server:
  port: 8084

spring:
  datasource:
    url: jdbc:postgresql://postgres-geo:5432/geolocalisation_db
    username: ${GEO_DB_USER:wasalny_user}
    password: ${GEO_DB_PASSWORD:wasalny_password}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  redis:
    host: ${SPRING_REDIS_HOST:redis}
    port: 6379
    password: ${SPRING_REDIS_PASSWORD:redis_password}

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/

security:
  jwt:
    secret-key: ${JWT_SECRET:yPBDF3goXOTLVXbA4VFPTmOFcXtNT8ouT80zRJV3tecvi/SJCDU8makhpYKWX30a0kW7ANe5OhLC2ToJ3Zbd4Q==}
    expiration-time: ${JWT_EXPIRATION:86400000}