server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://postgres-trajet:5432/trajet_db
    username: ${TRAJET_DB_USER:wasalny_user}
    password: ${TRAJET_DB_PASSWORD:wasalny_password}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

geolocalisation:
  service:
    url: ${GEOLOCALISATION_SERVICE_URL:http://localhost:8084}

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/

security:
  jwt:
    secret-key: ${JWT_SECRET:yPBDF3goXOTLVXbA4VFPTmOFcXtNT8ouT80zRJV3tecvi/SJCDU8makhpYKWX30a0kW7ANe5OhLC2ToJ3Zbd4Q==}
    expiration-time: ${JWT_EXPIRATION:86400000}